/* ESPACE ENSEIGNANT HASSINI — Agenda intelligent, socle commun v1.1.0 — reprogrammation */
(function(global){
'use strict';
const STORAGE_KEY='hassini_agenda_core_2026_2027';
const VERSION=2;
const TYPES=new Set(['seance','echeance','reunion','absence','annulation','sortie','stage','examen','conseil','rdv','rappel','autre']);
const STATUSES=new Set(['prevue','realisee','partielle','annulee','reportee','a_reprogrammer']);
const PRIORITIES=new Set(['basse','normale','haute','critique']);
function now(){return new Date().toISOString()}
function uid(){return 'hev_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,10)}
function empty(){return {version:VERSION,updatedAt:now(),events:[]}}
function read(){try{const x=JSON.parse(localStorage.getItem(STORAGE_KEY)||'null');if(!x||!Array.isArray(x.events))return empty();return {version:VERSION,updatedAt:x.updatedAt||now(),events:x.events.map(normalize)}}catch(e){return empty()}}
function write(db,reason){db.version=VERSION;db.updatedAt=now();localStorage.setItem(STORAGE_KEY,JSON.stringify(db));global.dispatchEvent(new CustomEvent('hassini-agenda-change',{detail:{reason:reason||'update',updatedAt:db.updatedAt}}));return db}
function isoDate(v){if(!v)return '';const s=String(v).slice(0,10);return /^\d{4}-\d{2}-\d{2}$/.test(s)?s:''}
function hhmm(v){if(!v)return '';const s=String(v).slice(0,5);return /^([01]\d|2[0-3]):[0-5]\d$/.test(s)?s:''}
function normalize(e){e=e||{};return {
 id:e.id||uid(), type:TYPES.has(e.type)?e.type:'autre', title:String(e.title||'').trim(),
 date:isoDate(e.date), start:hhmm(e.start), end:hhmm(e.end), allDay:!!e.allDay,
 classId:String(e.classId||'').trim(), level:String(e.level||'').trim(), room:String(e.room||'').trim(),
 subject:String(e.subject||'').trim(), sessionId:String(e.sessionId||'').trim(), sequenceId:String(e.sequenceId||'').trim(),
 status:STATUSES.has(e.status)?e.status:'prevue', priority:PRIORITIES.has(e.priority)?e.priority:'normale',
 reason:String(e.reason||'').trim(), notes:String(e.notes||'').trim(), source:String(e.source||'').trim(),
 blocksSession:!!e.blocksSession, linkedEventId:String(e.linkedEventId||'').trim(),
 pedagogical:{planned:String(e.pedagogical&&e.pedagogical.planned||''),done:String(e.pedagogical&&e.pedagogical.done||''),remaining:String(e.pedagogical&&e.pedagogical.remaining||''),progress:Math.max(0,Math.min(100,Number(e.pedagogical&&e.pedagogical.progress)||0))},
 alert:{enabled:!!(e.alert&&e.alert.enabled),daysBefore:Math.max(0,Number(e.alert&&e.alert.daysBefore)||0),acknowledged:!!(e.alert&&e.alert.acknowledged)},
 createdAt:e.createdAt||now(),updatedAt:e.updatedAt||now()
}}
function validate(e){const n=normalize(e),errors=[];if(!n.title)errors.push('title');if(!n.date)errors.push('date');if(!n.allDay&&n.start&&n.end&&n.end<=n.start)errors.push('timeRange');return {ok:errors.length===0,errors,event:n}}
function upsert(e){const v=validate(e);if(!v.ok)throw new Error('Événement invalide: '+v.errors.join(', '));const db=read(),i=db.events.findIndex(x=>x.id===v.event.id);v.event.updatedAt=now();if(i<0)db.events.push(v.event);else{v.event.createdAt=db.events[i].createdAt;db.events[i]=v.event}write(db,i<0?'create':'update');return v.event}
function remove(id){const db=read(),n=db.events.length;db.events=db.events.filter(e=>e.id!==id);if(db.events.length!==n)write(db,'delete');return db.events.length!==n}
function list(filter){let a=read().events.slice();filter=filter||{};if(filter.date)a=a.filter(e=>e.date===filter.date);if(filter.classId)a=a.filter(e=>e.classId===filter.classId);if(filter.type)a=a.filter(e=>e.type===filter.type);if(filter.status)a=a.filter(e=>e.status===filter.status);return a.sort((x,y)=>(x.date+x.start).localeCompare(y.date+y.start))}
function conflicts(candidate){const c=normalize(candidate);if(!c.date||!c.start||!c.end)return [];return list({date:c.date}).filter(e=>e.id!==c.id&&e.start&&e.end&&c.start<e.end&&c.end>e.start)}
function blockingEventsForSession(session){const s=session||{};if(!s.date)return[];return list({date:s.date}).filter(e=>e.blocksSession&&e.status!=='annulee').filter(e=>{if(e.classId&&s.classId&&e.classId!==s.classId)return false;if(!e.start||!e.end||!s.start||!s.end)return true;return e.start<s.end&&e.end>s.start})}
function isSessionBlocked(session){return blockingEventsForSession(session).length>0}
function markSession(id,status,details){if(!STATUSES.has(status))throw new Error('Statut inconnu');const db=read(),e=db.events.find(x=>x.id===id);if(!e)throw new Error('Séance introuvable');e.status=status;e.updatedAt=now();details=details||{};if(details.reason!==undefined)e.reason=String(details.reason||'');if(details.done!==undefined)e.pedagogical.done=String(details.done||'');if(details.remaining!==undefined)e.pedagogical.remaining=String(details.remaining||'');if(details.progress!==undefined)e.pedagogical.progress=Math.max(0,Math.min(100,Number(details.progress)||0));if(status==='annulee'||status==='partielle')e.status=status;write(db,'session-status');return e}
function dueAlerts(onDate){const target=isoDate(onDate)||new Date().toISOString().slice(0,10);const t=new Date(target+'T12:00:00');return read().events.filter(e=>e.alert.enabled&&!e.alert.acknowledged&&e.date).filter(e=>{const d=new Date(e.date+'T12:00:00');return Math.ceil((d-t)/86400000)<=e.alert.daysBefore&&d>=t}).sort((a,b)=>a.date.localeCompare(b.date))}
function subscribe(fn){const local=e=>fn(e.detail||{}),storage=e=>{if(e.key===STORAGE_KEY)fn({reason:'storage',updatedAt:now()})};global.addEventListener('hassini-agenda-change',local);global.addEventListener('storage',storage);return ()=>{global.removeEventListener('hassini-agenda-change',local);global.removeEventListener('storage',storage)}}
function diagnostics(){const db=read();return {ok:true,version:VERSION,storageKey:STORAGE_KEY,eventCount:db.events.length,updatedAt:db.updatedAt}}
global.HassiniAgendaCore={VERSION,STORAGE_KEY,TYPES:[...TYPES],STATUSES:[...STATUSES],PRIORITIES:[...PRIORITIES],read,list,validate,upsert,remove,conflicts,blockingEventsForSession,isSessionBlocked,markSession,dueAlerts,subscribe,diagnostics};
})(window);

/* ===== ÉTAPE 2 · Éditeur interactif + détection d'impact ===== */
(function(global){
'use strict';
const core=global.HassiniAgendaCore;if(!core)return;
let providers=[],selectedDate='';
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function registerSessionProvider(fn){if(typeof fn==='function')providers.push(fn);return ()=>{providers=providers.filter(x=>x!==fn)}}
function sessionsForDate(date){return providers.flatMap(fn=>{try{return fn(date)||[]}catch(e){return []}}).filter(Boolean)}
function impacts(candidate){const c=core.validate(candidate).event;if(!c.date)return[];const sessions=sessionsForDate(c.date);if(!c.blocksSession)return[];return sessions.filter(s=>{if(c.classId&&s.classId&&c.classId!==s.classId)return false;if(!c.start||!c.end||!s.start||!s.end)return true;return c.start<s.end&&c.end>s.start})}
function inject(){if(document.getElementById('hai-style'))return;const st=document.createElement('style');st.id='hai-style';st.textContent=`
.hai-fab{position:fixed;right:20px;bottom:20px;z-index:2147482000;border:0;border-radius:999px;background:#0D1B2A;color:#fff;padding:11px 16px;font:700 13px system-ui;box-shadow:0 8px 28px #0003;cursor:pointer}.hai-fab b{color:#D4B87A}.hai-back{display:none;position:fixed;inset:0;background:#08131f99;z-index:2147483000;align-items:center;justify-content:center;padding:18px}.hai-back.open{display:flex}.hai-modal{width:min(720px,96vw);max-height:92vh;overflow:auto;background:#fff;border-radius:18px;box-shadow:0 24px 70px #0005;font:14px system-ui;color:#17202a}.hai-head{padding:18px 20px;background:#0D1B2A;color:#fff;border-radius:18px 18px 0 0;display:flex;justify-content:space-between;gap:12px}.hai-head h3{margin:0;font-size:18px}.hai-head small{color:#D4B87A}.hai-close{border:0;background:transparent;color:#fff;font-size:25px;cursor:pointer}.hai-body{padding:18px 20px}.hai-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.hai-grid label{display:grid;gap:5px;font-weight:700;font-size:12px}.hai-grid .wide{grid-column:1/-1}.hai-grid input,.hai-grid select,.hai-grid textarea{width:100%;border:1px solid #d7dde3;border-radius:9px;padding:9px;font:inherit;background:#fff}.hai-grid textarea{min-height:70px;resize:vertical}.hai-check{display:flex!important;align-items:center;grid-template-columns:auto 1fr!important;gap:8px!important}.hai-check input{width:auto}.hai-impact{margin-top:12px;padding:11px;border-radius:10px;background:#fff6df;border:1px solid #e5c16d;display:none}.hai-impact.show{display:block}.hai-events{margin-top:15px;border-top:1px solid #e7eaee;padding-top:12px}.hai-event{display:flex;justify-content:space-between;gap:10px;padding:8px 0;border-bottom:1px solid #eef0f2}.hai-actions{display:flex;justify-content:flex-end;gap:8px;margin-top:16px}.hai-btn{border:1px solid #ccd3da;border-radius:9px;padding:9px 13px;background:#fff;font-weight:700;cursor:pointer}.hai-btn.primary{background:#0D1B2A;color:#fff;border-color:#0D1B2A}.hai-btn.danger{color:#9d2b2b}.hai-note{font-size:12px;color:#66717c;margin-top:8px}@media(max-width:620px){.hai-grid{grid-template-columns:1fr}.hai-grid .wide{grid-column:auto}.hai-fab{right:12px;bottom:12px}}
`;document.head.appendChild(st);
const wrap=document.createElement('div');wrap.innerHTML=`<button class="hai-fab" id="haiFab" type="button"><b>＋</b> Agenda intelligent</button><div class="hai-back" id="haiBack"><section class="hai-modal" role="dialog" aria-modal="true"><div class="hai-head"><div><h3>Agenda intelligent</h3><small id="haiDateLabel">Événement</small></div><button class="hai-close" id="haiClose">×</button></div><div class="hai-body"><form id="haiForm"><input type="hidden" id="haiId"><div class="hai-grid"><label class="wide">Titre<input id="haiTitle" required placeholder="Réunion, échéance, sortie…"></label><label>Date<input id="haiDate" type="date" required></label><label>Type<select id="haiType"><option value="reunion">Réunion</option><option value="echeance">Échéance</option><option value="annulation">Cours annulé</option><option value="sortie">Sortie</option><option value="absence">Absence</option><option value="stage">Stage</option><option value="examen">Examen</option><option value="conseil">Conseil</option><option value="rdv">Rendez-vous</option><option value="rappel">Rappel</option><option value="autre">Autre</option></select></label><label>Début<input id="haiStart" type="time"></label><label>Fin<input id="haiEnd" type="time"></label><label>Classe / groupe<input id="haiClass" placeholder="ex. 3C"></label><label>Priorité<select id="haiPriority"><option>basse</option><option selected>normale</option><option>haute</option><option>critique</option></select></label><label class="wide hai-check"><input id="haiBlocks" type="checkbox"><span>Cet événement remplace ou empêche une séance prévue</span></label><label class="wide">Motif / notes<textarea id="haiNotes"></textarea></label></div><div class="hai-impact" id="haiImpact"></div><div class="hai-actions"><button type="button" class="hai-btn danger" id="haiDelete" hidden>Supprimer</button><button type="button" class="hai-btn" id="haiNew">Nouveau</button><button class="hai-btn primary">Enregistrer</button></div></form><div class="hai-events"><b>Événements de cette date</b><div id="haiList"></div></div><div class="hai-note">Les séances détectées comme impactées sont signalées ici. Toute séance bloquée est désormais neutralisée dans la progression : son contenu bascule sur la prochaine séance disponible de la même classe.</div></div></section></div>`;document.body.appendChild(wrap);
const $=id=>document.getElementById(id),back=$('haiBack'),form=$('haiForm');
function currentDate(){return $('haiDate').value||selectedDate||new Date().toISOString().slice(0,10)}
function draft(){return {id:$('haiId').value||undefined,title:$('haiTitle').value,date:$('haiDate').value,type:$('haiType').value,start:$('haiStart').value,end:$('haiEnd').value,classId:$('haiClass').value,priority:$('haiPriority').value,blocksSession:$('haiBlocks').checked,notes:$('haiNotes').value,source:document.title}}
function renderImpact(){const a=impacts(draft()),box=$('haiImpact');if(!$('haiBlocks').checked){box.classList.remove('show');return}box.classList.add('show');box.innerHTML=a.length?`<b>⚠ ${a.length} séance${a.length>1?'s':''} impactée${a.length>1?'s':''}</b><br>${a.map(s=>`${esc(s.start||'')}–${esc(s.end||'')} · ${esc(s.classId||'')} ${esc(s.subject||'')}`).join('<br>')}`:'<b>✓ Aucune séance détectée sur ce créneau.</b>'}
function renderList(){const date=currentDate();$('haiDateLabel').textContent=new Date(date+'T12:00:00').toLocaleDateString('fr-FR',{weekday:'long',day:'numeric',month:'long',year:'numeric'});const a=core.list({date});$('haiList').innerHTML=a.length?a.map(e=>`<div class="hai-event"><span><b>${esc(e.title)}</b><br><small>${esc(e.type)}${e.start?' · '+esc(e.start)+(e.end?'–'+esc(e.end):''):''}${e.classId?' · '+esc(e.classId):''}</small></span><button type="button" class="hai-btn" data-hai-edit="${esc(e.id)}">Modifier</button></div>`).join(''):'<div class="hai-note">Aucun événement enregistré.</div>';document.querySelectorAll('[data-hai-edit]').forEach(b=>b.onclick=()=>load(b.dataset.haiEdit))}
function clear(date){form.reset();$('haiId').value='';$('haiDate').value=date||currentDate();$('haiType').value='reunion';$('haiPriority').value='normale';$('haiDelete').hidden=true;renderImpact();renderList()}
function load(id){const e=core.read().events.find(x=>x.id===id);if(!e)return;$('haiId').value=e.id;$('haiTitle').value=e.title;$('haiDate').value=e.date;$('haiType').value=e.type;$('haiStart').value=e.start;$('haiEnd').value=e.end;$('haiClass').value=e.classId;$('haiPriority').value=e.priority;$('haiBlocks').checked=e.blocksSession;$('haiNotes').value=e.notes||e.reason;$('haiDelete').hidden=false;renderImpact();renderList()}
function open(date){selectedDate=date||selectedDate||new Date().toISOString().slice(0,10);back.classList.add('open');clear(selectedDate);setTimeout(()=>$('haiTitle').focus(),0)}
function close(){back.classList.remove('open')}
$('haiFab').onclick=()=>open();$('haiClose').onclick=close;back.onclick=e=>{if(e.target===back)close()};$('haiNew').onclick=()=>clear(currentDate());$('haiDelete').onclick=()=>{const id=$('haiId').value;if(id&&confirm('Supprimer cet événement ?')){core.remove(id);clear(currentDate())}};form.oninput=()=>{selectedDate=$('haiDate').value||selectedDate;renderImpact();renderList()};form.onsubmit=e=>{e.preventDefault();const ev=core.upsert(draft());selectedDate=ev.date;load(ev.id)};document.addEventListener('keydown',e=>{if(e.key==='Escape'&&back.classList.contains('open'))close()});document.addEventListener('click',e=>{const cell=e.target.closest('[data-calendar-date],[data-date]');if(cell)selectedDate=cell.dataset.calendarDate||cell.dataset.date||selectedDate},true);
global.HassiniAgendaUI={open,close,selectDate:d=>selectedDate=d,impacts,sessionsForDate};
}
core.registerSessionProvider=registerSessionProvider;core.sessionsForDate=sessionsForDate;core.impacts=impacts;
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',inject);else inject();
})(window);

/* ===== ÉTAPE 4 · VISUALISATION DES RECALAGES DANS LES CALENDRIERS ===== */
(function(global){
'use strict';
const core=global.HassiniAgendaCore;if(!core)return;
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function addDays(iso,n){const d=new Date(iso+'T12:00:00');d.setDate(d.getDate()+n);return d.toISOString().slice(0,10)}
function sameKind(a,b){if(a.classId&&b.classId&&a.classId!==b.classId)return false;if(a.subject&&b.subject&&a.subject!==b.subject)return false;return true}
function nextAvailableSession(session,afterDate,maxDays){maxDays=Math.max(1,Number(maxDays)||370);if(!session||!session.classId||!afterDate||typeof core.sessionsForDate!=='function')return null;for(let i=1;i<=maxDays;i++){const date=addDays(afterDate,i);const candidates=(core.sessionsForDate(date)||[]).filter(x=>sameKind(session,x));for(const c of candidates){const candidate=Object.assign({date},c);if(!core.isSessionBlocked(candidate))return candidate;}}return null}
function reprogrammingForEvent(event){if(!event||!event.blocksSession||event.status==='annulee'||typeof core.impacts!=='function')return[];return (core.impacts(event)||[]).map(source=>({event,source,destination:nextAvailableSession(source,event.date)}))}
function reprogrammingForDate(date){return core.list({date}).flatMap(reprogrammingForEvent)}
function allReprogrammings(){return core.read().events.filter(e=>e.blocksSession&&e.status!=='annulee').flatMap(reprogrammingForEvent)}
function fmt(iso){if(!iso)return 'date à déterminer';try{return new Date(iso+'T12:00:00').toLocaleDateString('fr-FR',{weekday:'short',day:'2-digit',month:'2-digit'})}catch(e){return iso}}
function ensureUI(){if(document.getElementById('hai-reprog-style'))return;const st=document.createElement('style');st.id='hai-reprog-style';st.textContent=`.hai-reprog{margin-top:14px;border-top:1px solid #e7eaee;padding-top:12px}.hai-reprog-title{display:flex;justify-content:space-between;align-items:center;gap:8px;margin-bottom:7px}.hai-reprog-count{min-width:23px;height:23px;border-radius:999px;background:#7b2d26;color:#fff;display:inline-flex;align-items:center;justify-content:center;font-size:11px;font-weight:800}.hai-reprog-row{padding:9px 10px;border-left:4px solid #c77b30;background:#fff8eb;border-radius:8px;margin:7px 0;font-size:12px;line-height:1.45}.hai-reprog-row b{color:#7b2d26}.hai-reprog-arrow{font-weight:900;color:#7b2d26;padding:0 4px}.hai-cal-event,.hai-cal-blocked{position:relative!important}.hai-cal-dot{position:absolute;top:3px;right:3px;z-index:8;display:flex;align-items:center;justify-content:center;width:18px;height:18px;border-radius:999px;background:#0D1B2A;color:#fff;font:800 11px/1 system-ui;box-shadow:0 1px 5px #0004;pointer-events:none}.hai-cal-blocked>.hai-cal-dot{background:#a43d32}.hai-cal-blocked{outline:2px solid rgba(164,61,50,.45);outline-offset:-2px}.hai-cal-event:not(.hai-cal-blocked){outline:1px solid rgba(13,27,42,.25);outline-offset:-1px}`;document.head.appendChild(st);const body=document.querySelector('.hai-body');if(body&&!document.getElementById('haiReprog')){const box=document.createElement('div');box.id='haiReprog';box.className='hai-reprog';const events=body.querySelector('.hai-events');if(events)events.insertAdjacentElement('afterend',box);else body.appendChild(box)}}
function modalDate(){const d=document.getElementById('haiDate');return d&&d.value?d.value:new Date().toISOString().slice(0,10)}
function render(date){ensureUI();const box=document.getElementById('haiReprog');if(!box)return;const rows=reprogrammingForDate(date||modalDate());box.innerHTML=`<div class="hai-reprog-title"><b>↻ Reprogrammation pédagogique</b><span class="hai-reprog-count">${rows.length}</span></div>`+(rows.length?rows.map(r=>{const s=r.source,d=r.destination;const left=`${esc(fmt(r.event.date))} · ${esc(s.start||'')}–${esc(s.end||'')} · ${esc(s.classId||'')}`;const right=d?`${esc(fmt(d.date))} · ${esc(d.start||'')}–${esc(d.end||'')}`:'aucun créneau disponible détecté';return `<div class="hai-reprog-row"><b>${esc(r.event.title||'Séance empêchée')}</b><br>${left}<span class="hai-reprog-arrow"> → </span>${right}${r.event.reason||r.event.notes?`<br><small>Motif : ${esc(r.event.reason||r.event.notes)}</small>`:''}</div>`}).join(''):'<div class="hai-note">Aucun décalage pédagogique détecté pour cette date.</div>')}
let timer=0;function decorate(){clearTimeout(timer);timer=setTimeout(()=>{document.querySelectorAll('[data-calendar-date],[data-date]').forEach(cell=>{const date=cell.dataset.calendarDate||cell.dataset.date||'';if(!/^\d{4}-\d{2}-\d{2}$/.test(date))return;cell.classList.remove('hai-cal-event','hai-cal-blocked');const old=cell.querySelector(':scope > .hai-cal-dot');if(old)old.remove();const evs=core.list({date}),reps=reprogrammingForDate(date);if(!evs.length)return;cell.classList.add('hai-cal-event');if(reps.length)cell.classList.add('hai-cal-blocked');const dot=document.createElement('span');dot.className='hai-cal-dot';dot.textContent=reps.length?'↻':'•';cell.appendChild(dot);if(!cell.dataset.haiBaseTitle)cell.dataset.haiBaseTitle=cell.getAttribute('title')||'';const extra=reps.length?`${reps.length} séance${reps.length>1?'s':''} reprogrammée${reps.length>1?'s':''}`:`${evs.length} événement${evs.length>1?'s':''}`;cell.setAttribute('title',(cell.dataset.haiBaseTitle?cell.dataset.haiBaseTitle+' · ':'')+'Agenda intelligent · '+extra)})},40)}
function refresh(){render(modalDate());decorate()}
function hook(){ensureUI();refresh();if(core.subscribe)core.subscribe(refresh);document.addEventListener('input',e=>{if(e.target&&e.target.closest&&e.target.closest('#haiForm'))setTimeout(refresh,0)},true);document.addEventListener('click',e=>{if(e.target&&e.target.closest&&e.target.closest('[data-calendar-date],[data-date]'))setTimeout(refresh,0)},true);const mo=new MutationObserver(decorate);mo.observe(document.body,{subtree:true,childList:true})}
core.nextAvailableSession=nextAvailableSession;core.reprogrammingForEvent=reprogrammingForEvent;core.reprogrammingForDate=reprogrammingForDate;core.allReprogrammings=allReprogrammings;core.refreshCalendarMarkers=decorate;if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',hook);else hook();
})(window);


/* ===== ÉTAPE 5 · SÉANCES PARTIELLES, RELIQUAT ET HISTORIQUE ===== */
(function(global){
'use strict';
const core=global.HassiniAgendaCore;if(!core)return;
const KEY='hassini_session_progress_2026_2027';
function now(){return new Date().toISOString()}
function readProgress(){try{const x=JSON.parse(localStorage.getItem(KEY)||'{}');return x&&typeof x==='object'?x:{}}catch(e){return {}}}
function sessionKey(s){return [s.classId||'',s.sequenceId||'',s.sessionId||''].join('|')}
function normalize(s,d){d=d||{};return {key:sessionKey(s),classId:String(s.classId||''),sequenceId:String(s.sequenceId||''),sessionId:String(s.sessionId||''),subject:String(s.subject||'Espagnol LV2'),date:String(d.date||s.date||'').slice(0,10),status:d.status==='realisee'?'realisee':d.status==='annulee'?'annulee':'partielle',progress:Math.max(0,Math.min(100,Number(d.progress)||0)),done:String(d.done||''),remaining:String(d.remaining||''),mode:String(d.mode||''),updatedAt:now()}}
function setSessionProgress(s,d){const k=sessionKey(s);if(!k.replace(/\|/g,''))throw new Error('Séance non identifiable');const db=readProgress(),r=normalize(s,d);db[k]=r;localStorage.setItem(KEY,JSON.stringify(db));global.dispatchEvent(new CustomEvent('hassini-session-progress-change',{detail:r}));return r}
function getSessionProgress(s){return readProgress()[typeof s==='string'?s:sessionKey(s)]||null}
function listSessionProgress(filter){filter=filter||{};return Object.values(readProgress()).filter(r=>(!filter.classId||r.classId===filter.classId)&&(!filter.status||r.status===filter.status)).sort((a,b)=>(b.date+b.updatedAt).localeCompare(a.date+a.updatedAt))}
function partialSessions(){return listSessionProgress({status:'partielle'}).filter(r=>r.progress<100)}
function clearSessionProgress(s){const db=readProgress(),k=typeof s==='string'?s:sessionKey(s);if(!(k in db))return false;delete db[k];localStorage.setItem(KEY,JSON.stringify(db));global.dispatchEvent(new CustomEvent('hassini-session-progress-change',{detail:{key:k,deleted:true}}));return true}
core.SESSION_PROGRESS_KEY=KEY;core.sessionKey=sessionKey;core.setSessionProgress=setSessionProgress;core.getSessionProgress=getSessionProgress;core.listSessionProgress=listSessionProgress;core.partialSessions=partialSessions;core.clearSessionProgress=clearSessionProgress;
function esc(x){return String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function injectSummary(){if(document.getElementById('haiPartialSummary'))return;const body=document.querySelector('.hai-body');if(!body)return;const box=document.createElement('div');box.id='haiPartialSummary';box.className='hai-reprog';body.appendChild(box);render()}
function render(){injectSummary();const box=document.getElementById('haiPartialSummary');if(!box)return;const rows=partialSessions();box.innerHTML=`<div class="hai-reprog-title"><b>◔ Séances à poursuivre</b><span class="hai-reprog-count">${rows.length}</span></div>`+(rows.length?rows.slice(0,8).map(r=>`<div class="hai-reprog-row"><b>${esc(r.classId)} · Séq. ${esc(r.sequenceId)} · S${esc(r.sessionId)} — ${r.progress}%</b>${r.remaining?`<br><small>À poursuivre : ${esc(r.remaining)}</small>`:''}${r.date?`<br><small>Dernière séance : ${esc(new Date(r.date+'T12:00:00').toLocaleDateString('fr-FR'))}</small>`:''}</div>`).join(''):'<div class="hai-note">Aucune séance partiellement réalisée en attente.</div>')}
function hook(){injectSummary();global.addEventListener('hassini-session-progress-change',render);if(core.subscribe)core.subscribe(render)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',hook);else hook();
})(window);


/* ===== ÉTAPE 6 · ÉCHÉANCES & ALERTES INTELLIGENTES ===== */
(function(global){
'use strict';
const core=global.HassiniAgendaCore;if(!core)return;
const DEADLINE_TYPES=new Set(['echeance','examen','conseil','rdv','stage','rappel']);
const PRIORITY_WEIGHT={critique:4,haute:3,normale:2,basse:1};
const DEFAULT_DAYS={critique:14,haute:7,normale:3,basse:1};
function today(){return new Date().toISOString().slice(0,10)}
function dayDiff(from,to){const a=new Date(from+'T12:00:00'),b=new Date(to+'T12:00:00');return Math.round((b-a)/86400000)}
function labelPriority(p){return ({critique:'Critique',haute:'Haute',normale:'Normale',basse:'Basse'})[p]||'Normale'}
function defaultReminderDays(priority){return DEFAULT_DAYS[priority]??3}
function shouldAutoAlert(e){return DEADLINE_TYPES.has(e&&e.type)}
function alertState(e,onDate){const ref=onDate||today(),d=dayDiff(ref,e.date);let state='future';if(d<0)state='overdue';else if(d===0)state='today';else if(e.alert&&e.alert.enabled&&d<=Number(e.alert.daysBefore||0))state='due';return {days:d,state}}
function smartAlerts(onDate){const ref=onDate||today();return core.read().events.filter(e=>e.date&&e.status!=='annulee'&&e.alert&&e.alert.enabled&&!e.alert.acknowledged).map(e=>({event:e,...alertState(e,ref)})).filter(x=>x.days<=Number(x.event.alert.daysBefore||0)||x.days<0).sort((a,b)=>{const sa=a.state==='overdue'?4:a.state==='today'?3:a.state==='due'?2:1,sb=b.state==='overdue'?4:b.state==='today'?3:b.state==='due'?2:1;return sb-sa||(PRIORITY_WEIGHT[b.event.priority]||0)-(PRIORITY_WEIGHT[a.event.priority]||0)||a.event.date.localeCompare(b.event.date)})}
function upcomingDeadlines(days,onDate){days=Math.max(1,Number(days)||30);const ref=onDate||today();return core.read().events.filter(e=>e.date&&e.status!=='annulee'&&(DEADLINE_TYPES.has(e.type)||e.alert&&e.alert.enabled)).map(e=>({event:e,...alertState(e,ref)})).filter(x=>x.days>=0&&x.days<=days).sort((a,b)=>a.days-b.days||(PRIORITY_WEIGHT[b.event.priority]||0)-(PRIORITY_WEIGHT[a.event.priority]||0))}
function setAlert(id,enabled,daysBefore){const e=core.read().events.find(x=>x.id===id);if(!e)throw new Error('Événement introuvable');e.alert={enabled:!!enabled,daysBefore:Math.max(0,Number(daysBefore)||0),acknowledged:false};return core.upsert(e)}
function acknowledgeAlert(id,ack){const e=core.read().events.find(x=>x.id===id);if(!e)throw new Error('Événement introuvable');e.alert=e.alert||{enabled:true,daysBefore:defaultReminderDays(e.priority),acknowledged:false};e.alert.acknowledged=ack!==false;return core.upsert(e)}
function ensureAutoAlert(id){const e=core.read().events.find(x=>x.id===id);if(!e)return null;if(shouldAutoAlert(e)&&(!e.alert||!e.alert.enabled)&&!e.alert?.acknowledged){e.alert={enabled:true,daysBefore:defaultReminderDays(e.priority),acknowledged:false};return core.upsert(e)}return e}
core.smartAlerts=smartAlerts;core.upcomingDeadlines=upcomingDeadlines;core.alertState=alertState;core.defaultReminderDays=defaultReminderDays;core.setAlert=setAlert;core.acknowledgeAlert=acknowledgeAlert;core.ensureAutoAlert=ensureAutoAlert;

function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function fmtDate(iso){try{return new Date(iso+'T12:00:00').toLocaleDateString('fr-FR',{weekday:'short',day:'2-digit',month:'2-digit'})}catch(e){return iso}}
function ensureStyle(){if(document.getElementById('hai-alert-style'))return;const st=document.createElement('style');st.id='hai-alert-style';st.textContent=`
.hai-alert-config{grid-column:1/-1;padding:10px 12px;border-radius:10px;background:#f6f8fa;border:1px solid #dde3e8}.hai-alert-config .row{display:flex;align-items:center;gap:10px;flex-wrap:wrap}.hai-alert-config label{display:flex!important;align-items:center;gap:7px!important;font-weight:700}.hai-alert-config input[type=checkbox]{width:auto}.hai-alert-config select{width:auto!important;min-width:110px}.hai-alert-hint{font-size:11px;color:#66717c;margin-top:6px}.hai-alert-center{margin-top:14px;border-top:1px solid #e7eaee;padding-top:12px}.hai-alert-head{display:flex;justify-content:space-between;align-items:center;gap:8px;margin-bottom:7px}.hai-alert-count{min-width:24px;height:24px;border-radius:999px;background:#b33b32;color:#fff;display:inline-flex;align-items:center;justify-content:center;font-weight:900;font-size:11px}.hai-alert-row{border-left:4px solid #d6a53b;background:#fffaf0;border-radius:8px;padding:9px 10px;margin:7px 0;font-size:12px;line-height:1.45}.hai-alert-row.high{border-left-color:#d47b22;background:#fff5e8}.hai-alert-row.critical,.hai-alert-row.overdue{border-left-color:#b33b32;background:#fff0ef}.hai-alert-meta{color:#65717d}.hai-alert-actions{display:flex;gap:6px;margin-top:7px}.hai-alert-actions button{border:1px solid #d7dde3;border-radius:7px;background:#fff;padding:5px 8px;font:700 11px system-ui;cursor:pointer}.hai-alert-actions .ack{color:#26623b}.hai-deadline-row{padding:7px 9px;border-radius:8px;background:#f7f9fb;margin:6px 0;font-size:12px}.hai-fab{padding-right:42px!important}.hai-fab-badge{position:absolute;right:8px;top:50%;transform:translateY(-50%);min-width:24px;height:24px;padding:0 6px;border-radius:999px;background:#b33b32;color:#fff;display:none;align-items:center;justify-content:center;font:900 11px system-ui}.hai-fab.has-alerts .hai-fab-badge{display:flex}.hai-alert-dot{position:absolute;left:3px;top:3px;z-index:9;display:flex;align-items:center;justify-content:center;width:18px;height:18px;border-radius:999px;background:#d6a53b;color:#fff;font:900 11px/1 system-ui;box-shadow:0 1px 5px #0003;pointer-events:none}.hai-alert-dot.critical{background:#b33b32}.hai-alert-dot.high{background:#d47b22}`;document.head.appendChild(st)}
function formEls(){return {form:document.getElementById('haiForm'),type:document.getElementById('haiType'),priority:document.getElementById('haiPriority'),id:document.getElementById('haiId')}}
function ensureFormFields(){const {form}=formEls();if(!form||document.getElementById('haiAlertConfig'))return;const grid=form.querySelector('.hai-grid');if(!grid)return;const box=document.createElement('div');box.className='hai-alert-config';box.id='haiAlertConfig';box.innerHTML=`<div class="row"><label><input type="checkbox" id="haiAlertEnabled"> Rappel automatique</label><label>Délai <select id="haiAlertDays"><option value="0">le jour même</option><option value="1">1 jour avant</option><option value="2">2 jours avant</option><option value="3" selected>3 jours avant</option><option value="5">5 jours avant</option><option value="7">7 jours avant</option><option value="14">14 jours avant</option><option value="30">30 jours avant</option></select></label></div><div class="hai-alert-hint" id="haiAlertHint">Les échéances et rendez-vous peuvent générer automatiquement une alerte.</div>`;grid.appendChild(box)}
function ensurePanels(){const body=document.querySelector('.hai-body');if(!body)return;if(!document.getElementById('haiAlertCenter')){const box=document.createElement('div');box.id='haiAlertCenter';box.className='hai-alert-center';const ev=document.querySelector('.hai-events');if(ev)ev.insertAdjacentElement('beforebegin',box);else body.appendChild(box)}if(!document.getElementById('haiDeadlineCenter')){const box=document.createElement('div');box.id='haiDeadlineCenter';box.className='hai-alert-center';const partial=document.getElementById('haiPartialSummary');if(partial)partial.insertAdjacentElement('beforebegin',box);else body.appendChild(box)}const fab=document.getElementById('haiFab');if(fab&&!fab.querySelector('.hai-fab-badge')){const b=document.createElement('span');b.className='hai-fab-badge';b.id='haiFabBadge';fab.appendChild(b)}}
function eventForForm(){const id=document.getElementById('haiId')?.value;return id?core.read().events.find(e=>e.id===id):null}
function syncFormFromEvent(){ensureFormFields();const e=eventForForm(),type=document.getElementById('haiType')?.value||'reunion',priority=document.getElementById('haiPriority')?.value||'normale';const enabled=document.getElementById('haiAlertEnabled'),days=document.getElementById('haiAlertDays'),hint=document.getElementById('haiAlertHint');if(!enabled||!days)return;if(e){enabled.checked=!!e.alert?.enabled;days.value=String(e.alert?.daysBefore??defaultReminderDays(e.priority));hint.textContent=e.alert?.acknowledged?'Alerte acquittée. Toute modification du rappel la réactivera.':'Rappel '+(enabled.checked?'actif':'inactif')+' · priorité '+labelPriority(e.priority)+'.'}else{enabled.checked=shouldAutoAlert({type});days.value=String(defaultReminderDays(priority));hint.textContent=enabled.checked?'Rappel activé automatiquement pour ce type d’échéance.':'Activez un rappel si cet événement doit être signalé à l’avance.'}}
function persistFormAlert(){const id=document.getElementById('haiId')?.value,enabled=document.getElementById('haiAlertEnabled'),days=document.getElementById('haiAlertDays');if(!id||!enabled||!days)return;const e=core.read().events.find(x=>x.id===id);if(!e)return;const wanted={enabled:enabled.checked,daysBefore:Number(days.value)||0,acknowledged:false};if(!e.alert||e.alert.enabled!==wanted.enabled||Number(e.alert.daysBefore)!==wanted.daysBefore||e.alert.acknowledged){e.alert=wanted;core.upsert(e)}}
function renderCenters(){
  ensurePanels();
  const alerts=smartAlerts();
  const ab=document.getElementById('haiAlertCenter');
  const db=document.getElementById('haiDeadlineCenter');
  const fab=document.getElementById('haiFab');
  const badge=document.getElementById('haiFabBadge');
  if(ab){
    let html=`<div class="hai-alert-head"><b>🔔 Alertes actives</b><span class="hai-alert-count">${alerts.length}</span></div>`;
    if(alerts.length){
      html+=alerts.slice(0,10).map(x=>{
        const e=x.event;
        const cl=x.state==='overdue'?'overdue':e.priority==='critique'?'critical':e.priority==='haute'?'high':'';
        const when=x.state==='overdue'?`${Math.abs(x.days)} j de retard`:x.days===0?'aujourd’hui':`dans ${x.days} j`;
        return `<div class="hai-alert-row ${cl}"><b>${esc(e.title)}</b><br><span class="hai-alert-meta">${esc(fmtDate(e.date))} · ${esc(when)} · priorité ${esc(labelPriority(e.priority))}${e.classId?' · '+esc(e.classId):''}</span><div class="hai-alert-actions"><button type="button" data-hai-alert-view="${esc(e.id)}">Voir / modifier</button><button type="button" class="ack" data-hai-alert-ack="${esc(e.id)}">✓ Acquitter</button></div></div>`;
      }).join('');
    }else html+='<div class="hai-note">Aucune alerte à traiter aujourd’hui.</div>';
    ab.innerHTML=html;
    ab.querySelectorAll('[data-hai-alert-ack]').forEach(b=>b.onclick=()=>acknowledgeAlert(b.dataset.haiAlertAck,true));
    ab.querySelectorAll('[data-hai-alert-view]').forEach(b=>b.onclick=()=>openEvent(b.dataset.haiAlertView));
  }
  const ups=upcomingDeadlines(30);
  if(db){
    let html=`<div class="hai-alert-head"><b>📌 Prochaines échéances · 30 jours</b><span class="hai-reprog-count">${ups.length}</span></div>`;
    if(ups.length){
      html+=ups.slice(0,10).map(x=>`<div class="hai-deadline-row"><b>${esc(fmtDate(x.event.date))}</b> · ${esc(x.event.title)}${x.event.classId?' · '+esc(x.event.classId):''} <small>(${esc(labelPriority(x.event.priority))})</small></div>`).join('');
    }else html+='<div class="hai-note">Aucune échéance dans les 30 prochains jours.</div>';
    db.innerHTML=html;
  }
  if(fab&&badge){badge.textContent=String(alerts.length);fab.classList.toggle('has-alerts',alerts.length>0)}
}
function openEvent(id){const e=core.read().events.find(x=>x.id===id);if(!e)return;if(global.HassiniAgendaUI){global.HassiniAgendaUI.open(e.date);setTimeout(()=>{const b=document.querySelector(`[data-hai-edit="${CSS.escape(id)}"]`);if(b)b.click()},30)}}
let decorateTimer=0;function decorateCalendars(){clearTimeout(decorateTimer);decorateTimer=setTimeout(()=>{document.querySelectorAll('[data-calendar-date],[data-date]').forEach(cell=>{const date=cell.dataset.calendarDate||cell.dataset.date||'';if(!/^\d{4}-\d{2}-\d{2}$/.test(date))return;const old=cell.querySelector(':scope > .hai-alert-dot');if(old)old.remove();const evs=core.list({date}).filter(e=>e.status!=='annulee'&&(DEADLINE_TYPES.has(e.type)||e.alert?.enabled));if(!evs.length)return;const top=evs.sort((a,b)=>(PRIORITY_WEIGHT[b.priority]||0)-(PRIORITY_WEIGHT[a.priority]||0))[0];const dot=document.createElement('span');dot.className='hai-alert-dot '+(top.priority==='critique'?'critical':top.priority==='haute'?'high':'');dot.textContent=top.priority==='critique'?'!':'●';cell.appendChild(dot)})},60)}
function hook(){ensureStyle();ensureFormFields();ensurePanels();syncFormFromEvent();renderCenters();decorateCalendars();const f=document.getElementById('haiForm'),type=document.getElementById('haiType'),priority=document.getElementById('haiPriority');if(f){f.addEventListener('submit',()=>setTimeout(()=>{persistFormAlert();syncFormFromEvent();renderCenters();decorateCalendars()},0));f.addEventListener('input',e=>{if(e.target?.id==='haiAlertEnabled'||e.target?.id==='haiAlertDays')return;if(e.target===type||e.target===priority){const existing=eventForForm();if(!existing){const en=document.getElementById('haiAlertEnabled'),dy=document.getElementById('haiAlertDays');if(en)en.checked=shouldAutoAlert({type:type.value});if(dy)dy.value=String(defaultReminderDays(priority.value));}syncFormFromEvent()}})}document.addEventListener('click',e=>{if(e.target?.closest?.('[data-hai-edit]')||e.target?.id==='haiNew')setTimeout(syncFormFromEvent,0)},true);if(core.subscribe)core.subscribe(()=>{renderCenters();decorateCalendars()});global.addEventListener('hassini-session-progress-change',renderCenters);const mo=new MutationObserver(decorateCalendars);mo.observe(document.body,{subtree:true,childList:true})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',hook);else hook();
})(window);


/* ===== ÉTAPE 7 · SYNCHRONISATION TRANSVERSALE DES 3 OUTILS ===== */
(function(global){
'use strict';
const core=global.HassiniAgendaCore;if(!core)return;
const BRIDGE='__EHH_SYNC_2026_2027__', PROGRESS_KEY='hassini_session_progress_2026_2027';
function stamp(){return new Date().toISOString()}
function parseName(){try{const x=JSON.parse(global.name||'{}');return x&&typeof x==='object'?x:{}}catch(e){return {}}
}
function readBridge(){const x=parseName();const b=x[BRIDGE];return b&&typeof b==='object'?b:{version:1,updatedAt:'',events:[],progress:{}}}
function writeBridge(b){const x=parseName();x[BRIDGE]=b;try{global.name=JSON.stringify(x)}catch(e){}return b}
function eventTime(e){return String(e&&e.updatedAt||e&&e.createdAt||'')}
function mergeEvents(a,b){const m=new Map();[...(a||[]),...(b||[])].forEach(e=>{if(!e||!e.id)return;const old=m.get(e.id);if(!old||eventTime(e)>=eventTime(old))m.set(e.id,e)});return [...m.values()]}
function readProgress(){try{const x=JSON.parse(localStorage.getItem(PROGRESS_KEY)||'{}');return x&&typeof x==='object'?x:{}}catch(e){return {}}}
function mergeProgress(a,b){const out=Object.assign({},a||{});Object.entries(b||{}).forEach(([k,v])=>{if(!out[k]||String(v.updatedAt||'')>=String(out[k].updatedAt||''))out[k]=v});return out}
function exportBridge(reason){const b=readBridge(), db=core.read();b.version=1;b.updatedAt=stamp();b.reason=reason||'sync';b.events=mergeEvents(b.events,db.events);b.progress=mergeProgress(b.progress,readProgress());b.lastApp=document.title||'';writeBridge(b);return b}
function importBridge(){const b=readBridge();if(!b.updatedAt)return {events:0,progress:0};const local=core.read(), events=mergeEvents(local.events,b.events);let changed=JSON.stringify(events)!==JSON.stringify(local.events);if(changed){local.events=events;local.updatedAt=stamp();localStorage.setItem(core.STORAGE_KEY,JSON.stringify(local))}const lp=readProgress(), progress=mergeProgress(lp,b.progress);if(JSON.stringify(progress)!==JSON.stringify(lp))localStorage.setItem(PROGRESS_KEY,JSON.stringify(progress));return {events:events.length,progress:Object.keys(progress).length}}
function sync(reason){const imported=importBridge();const b=exportBridge(reason);global.dispatchEvent(new CustomEvent('ehh-sync-change',{detail:{reason:reason||'sync',updatedAt:b.updatedAt,events:b.events.length,progress:Object.keys(b.progress||{}).length}}));return Object.assign({ok:true,updatedAt:b.updatedAt},imported)}
function ensurePanel(){const body=document.querySelector('.hai-body');if(!body||document.getElementById('ehhSyncPanel'))return;const box=document.createElement('div');box.id='ehhSyncPanel';box.style.cssText='margin-top:14px;border-top:1px solid #e7eaee;padding-top:12px;font:12px system-ui;color:#56616c';body.appendChild(box);renderPanel()}
function renderPanel(){const box=document.getElementById('ehhSyncPanel');if(!box)return;const b=readBridge();const n=(b.events||[]).length,p=Object.keys(b.progress||{}).length;box.innerHTML='<b style="color:#17202a">⇄ Synchronisation EHH</b><br>Base commune : '+n+' événement'+(n>1?'s':'')+' · '+p+' suivi'+(p>1?'s':'')+' pédagogique'+(p>1?'s':'')+'<br><small>PP Premium · CAP-Español · Mon Suivi PP — fusion par identifiant et dernière modification, sans doublon.</small>'}
const originalUpsert=core.upsert, originalRemove=core.remove, originalMark=core.markSession;
core.upsert=function(){const r=originalUpsert.apply(core,arguments);exportBridge('event-upsert');renderPanel();return r};
core.remove=function(){const r=originalRemove.apply(core,arguments);exportBridge('event-delete');renderPanel();return r};
core.markSession=function(){const r=originalMark.apply(core,arguments);exportBridge('session-status');renderPanel();return r};
core.syncAll=sync;core.syncDiagnostics=function(){const b=readBridge();return {ok:true,bridge:BRIDGE,updatedAt:b.updatedAt||'',events:(b.events||[]).length,progress:Object.keys(b.progress||{}).length,lastApp:b.lastApp||''}};
function hook(){sync('startup');ensurePanel();if(core.subscribe)core.subscribe(()=>{exportBridge('agenda-change');renderPanel()});global.addEventListener('hassini-session-progress-change',()=>{exportBridge('progress-change');renderPanel()});global.addEventListener('pageshow',()=>{sync('pageshow');renderPanel()});global.addEventListener('pagehide',()=>exportBridge('pagehide'));document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden')exportBridge('hidden');else{sync('visible');renderPanel()}})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',hook);else hook();
})(window);
